---
- name: Configure common packages
  ansible.builtin.import_tasks: packages.yml
  tags: 
    - packages

- name: Configure users 
  ansible.builtin.import_tasks: users.yml
  tags:
    - users

- name: configure timezone  
  ansible.builtin.import_tasks: timezone.yml
  tags:
    - timezone

- name: Configure server security 
  ansible.builtin.import_tasks: security.yml
  tags:
    - security