---
- name: Configure SSH daemon 
  ansible.builtin.template:
    src: sshd_config.j2 
    dest: /etc/ssh/sshd_config
    owner: root
    group: root 
    mode: "0644"
    validate: "/usr/sbin/sshd -t -f %s"
  notify: Restart SSH
  tags:
    - ssh
  when: ansible_os_family == "Debian"

- name: Configure deafault incpming policy 
  community.general.ufw:
    direction: incoming 
    policy: "{{ ufw_default_incoming }}"

- name: Configure deafult outgoing policy 
  community.general.ufw:
    direction: outgoing 
    policy: "{{ ufw_default_outgoing }}"

- name: Allow required ports
  community.general.ufw:
    rule: allow 
    port: "{{ item.split('/')[0] }}"
    proto: "{{ item.split('/')[1] }}"
  loop: "{{ ufw_allowed_ports }}"

- name: Enable UFW
  community.general.ufw:
    state: enabled 
  tags:
    - firewall
  when:
  - ansible_os_family == "Debian"
  - enable_firewall


- name: Configure unattended upgrades
  ansible.builtin.template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt/conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: "0644"

- name: Configure automatic updates 
  ansible.builtin.template: 
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: "0644"
