---
- name: Configure monitoring with node exporter 
  hosts: monitoring 
  become: true 
  gather_facts: true

  vars:
    app_user: appuser
    node_exporter_port: 9100
    node_exporter_service: prometheus-node-exporter

    prometheus_server_ip: "192.168.1.0"

  tasks: 
    - name: Install node exporter and firewall packages
      ansible.builtin.apt:
        name:
          - prometheus-node-exporter
          - ufw
        state: present
        update_cache: true
        lock_timeout: 60

    - name: allow prometheus server to scrape NE port 
      community.general.ufw:
        rule: allow
        port: "{{ node_exporter_port }}"
        proto: tcp
        from_ip: "{{ prometheus_server_ip }}"
      when:
        - prometheus_server_ip is defined 
        - prometheus_server_ip | length > 0

    - name: enable and start NE
      ansible.builtin.systemd_service:
        name: "{{ node_exporter_service }}" 
        state: started
        enabled: true
        daemon_reload: true

    - name: check NE metrics endpoint 
      ansible.builtin.uri:
        url: "http://127.0.0.1:{{ node_exporter_port }}/metrics"
        status_code:
          - 200
        return_content: false
      register: node_export_check 
      
    - name: show node exporter check result
      ansible.builtin.debug:
        msg: "Node Exporter is dostupen na porty {{ node_exporter_port }}, HTTP status {{ node_export_check.status }}"
    
    - name: configure logrotate for myapp logs 
      ansible.builtin.template:
        src: ../templates/myapp-logrotate.j2
        dest: /etc/logrotate.d/myapp
        owner: root
        group: root
        mode: "0644"


  handlers:
    - name: Restart node_exporter 
      ansible.builtin.systemd_service:
        name: "{{ node_exporter_service }}"
        state: restarted
